### ISSUE TITLE
Instructions for stl2svg.pl?

### ISSUE THREAD

**Issue by Sjaak1** [gringer/bioinfscripts#1]
Could you explain how to use the stl2svg.pl script?

Thanks in advance!

**Comment by gringer** [comment]
1. Create an STL file which is orientated so that the Z axis points in the desired view direction [this creates an SVG file from a top-down view]
2. Run stl2svg on the STL file, and pipe the output to an SVG file name

Example OpenSCAD script to generate an STL file:

```
rotate([-45,0,0]) import("/home/gringer/models/halo/Halo_4_Helmet_Medium_Size_B/M_ChinFront_r1_0.stl");
```

Command line:

```
$ inkscape --export-dpi=600 --export-png=halo_example.png <(~/scripts/stl2svg.pl halo_example.stl)
```

Result:

![halo_example](https://cloud.githubusercontent.com/assets/856314/9479801/2630e518-4bd3-11e5-838d-2a4a19cfeb28.png)

I've added these instructions to the top of the perl script. I did submit this script to the OpenSCAD mailing list, and I think that the SVG output functionality of OpenSCAD has been modified to work in a similar way.
