### ISSUE TITLE
fastx-length.pl

### ISSUE THREAD

**Issue by sarah872** [gringer/bioinfscripts#5]
Hey, I am running into errors when executing the following code based on your tutorial:

`./fastx-length.pl PRJEB511.WBPS9.genomic.fa |gzip >lengths_Nb_WTSI.txt.gz`

```
Can't locate Digest/MD5.pm in @INC (@INC contains: /apps/perl/5.26.1/lib/perl5/x86_64-linux-thread-multi /apps/perl/5.26.1/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./fastx-length.pl line 7.
BEGIN failed--compilation aborted at ./fastx-length.pl line 7.
```

**Comment by gringer** [comment]
Hmm, I assumed that Digest::MD5 would be installed by default because it's on the list of [perl core modules](http://perldoc.perl.org/index-modules-D.html). Guess I was wrong about that.

This issue should be fixed by the following commit:

https://github.com/gringer/bioinfscripts/commit/ae325770eaf9efa52c851154fd8c7aabe221cd9f

If not, as a temporary fix, comment out the `use Digest::MD5 qw(md5_hex);` line.
